---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/coolb/Desktop/config


server:
  port: 8167
  
